query characters ($page: Int) {
  characters (page: $page) {
        results {
          id
          image
          name
          gender
          location {
            name
          }
        }
      }
}